### ISSUE TITLE
[infra] sucon-env-checker のパーミッションが間違えている

### ISSUE THREAD

**Issue by Mahito** [isucon/isucon11-qualify#1421]
```
- name: "roles/contestant.envchecker/tasks/main: Deploy isucon-env-checker"
  become_user: root
  copy:
    remote_src: yes
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: "0700"
  with_items:
    - src: /tmp/isucon11-qualify/extra/envchecker/isucon-env-checker/isucon-env-checker
      dst: /opt/isucon-env-checker/isucon-env-checker
    - src: /tmp/isucon11-qualify/extra/envchecker/run-isucon-env-checker.sh
      dst: /opt/isucon-env-checker/run-isucon-env-checker.sh
```

`isucon-env-checker` は 755 でした
